### ISSUE TITLE
Pretty-printing `Strs` in Python

### ISSUE THREAD

**Issue by ashvardanian** [ashvardanian/StringZilla#131]
The `Str` Python class already provides nice visualizations for Jupyter. Let's provide one for `Strs` and `File`.

![image](https://github.com/ashvardanian/StringZilla/assets/1983160/0b2ad990-cd16-4bf3-9ee2-1ec3bc6b826d)

**Comment by alexbowe** [comment]
Do we want the `File` representation to be similar to the Python built-in file type? That is, display the user-provided/default parameters rather than its (truncated) contents?

Here is an example of how Python does it:

```
>>> open("sample_data/california_housing_test.csv", "r")
<_io.TextIOWrapper name='sample_data/california_housing_test.csv' mode='r' encoding='UTF-8'>
```

Also, how is this for a representation of `Strs`: `sz.Strs([sz.Str('A'), sz.Str('B'), ..., sz.Str('Z')])`

(I _think_ Jupyter handles the truncation in its own formatter so the `Strs_repr` function might not need to consider it, but I need to look into that)

**Comment by ashvardanian** [comment]
@alexbowe, I think the `sz.Strs([sz.Str('A'), sz.Str('B'), ..., sz.Str('Z')])` may be too mouthful, but the `sz.Strs(['A', 'B', 'B'...])` would be great!
